introTab <-
  tabPanel(title = "Introduction",
    
    
    fluidRow(column(width = 3,
                    div(HTML("<img src='hexSticker.png' width='150px' height='150px'/>"))),
      
      column(
      width = 7,
      br(),
      HTML("Welcome to the <b>h</b>ealth <b>e</b>conomic <b>R</b>shiny <b>vis</b>ualisation builder (<b>heRvis</b>)."),
      br(),br(),
      p("Health Economists regularly use MS Excel to undertake Health Economic evaluations, however the plots generated by MS Excel often look very basic and dated.
        This tool allows users to take the outputs from an economic evaluation undertaken in MS Excel and create publication quality plots and tables within minutes.")
      
    )), # close column and row
    
    br(),br(),
    
    fluidRow(column(
      width = 10,
      offset = 1,
      p(
        "No programming knowledge is required. All the user needs to do is copy and paste their results into the tool, which will then create plots and tables using packages",
        tags$a(href = "https://rstudio.github.io/DT/options.html", "DT"),
        " & ",
        tags$a(href = "https://ggplot2.tidyverse.org/", "ggplot2"),
        "from R software environment in the background. Users can download the plots for use in reports."
      ),
      p("The tool is currently set up to create the following visuals:",
      tags$ul(
        tags$li("ICER-Table"), 
        tags$li("Cost-Effectiveness Plane"), 
        tags$li("Cost-Effectiveness Acceptability Curve(s)")
      )),
      
      
      p(
        "If you have any comments or suggestions feel free to contact us at: ",
        tags$a(href = "https://www.darkpeakanalytics.com/",
               "Dark Peak Analytics.")
      )
      
      
    ))#,
    # close column and row
    
    #fluidRow(
    #  HTML("<img src='rexcel1.png' width='400px' height='300px'/>"),
    #  
    #  align = "center"
    #)
    
    
    
  ) # close tabPanel
