introTab <- tabPanel("Introduction",
                fluidRow(column(width = 10,
                                offset = 1,
                                
                     p("Health Economists regularly use MS Excel to undertake Health Economic evaluations, however the plots generated by MS Excel often look very basic and dated."),
                     
                     p("This tool allows users to take the outputs from an economic evaluation undertaken in MS Excel and create publication quality plots and tables within minutes"),
                     
                     p("No programming knowledge is required. The app creates all plots using a variety of plotting packages available in R in the background"),
                     
                     p("These plots can then be downloaded and used in reports.")
                     
                )), # close column and row
                
                footer  # footer
                     
                     #p("If you have any comments or suggestions feel free to contact us at: ", tags$a(href="https://www.darkpeakanalytics.com/", "Dark Peak Analytics."))
                     
) # close tabpanel